apiVersion: v1
kind: Service
metadata:
  name: rancher-demo
  labels:
    app.kubernetes.io/name: rancher-demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rancher-demo