apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: device-priority
value: 100000
globalDefault: false
description: "This priority class should be used for deployments with hardware devices only"
