apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-green
  labels:
    app.kubernetes.io/name: rancher-demo
    app.kubernetes.io/instance: green
spec:
  replicas: 12
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
      app.kubernetes.io/instance: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-demo
        app.kubernetes.io/instance: green
        blinkt: show
        blinktColor: 00FF00
    spec:
      securityContext:
        {}
      containers:
        - name: rancher-green
          securityContext:
            {}
          image: "bgulla/rancher-demo:latest"
          imagePullPolicy: IfNotPresent
          env:          
          - name: COW_COLOR
            value: "green"
          - name: METADATA
            value: "Deployed via Fleet"
          - name: SHOW_VERSION
            value: "true"
          - name: VERSION
            value: "0.1"
          - name: TITLE
            value: "Rancher demo"  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 4m
              memory: 445Mi
            limits:    
              memory: 445Mi
      priorityClassName: low-priority
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rancher-demo-green
  labels:
    app.kubernetes.io/name: rancher-demo
    app.kubernetes.io/instance: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rancher-demo-green
  minReplicas: 2
  maxReplicas: 26
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
