apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-blue
  labels:
    app.kubernetes.io/name: rancher-demo
    app.kubernetes.io/instance: blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
      app.kubernetes.io/instance: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-demo
        app.kubernetes.io/instance: blue
        blinkt: show
        blinktColor: 0000FF
    spec:
      securityContext:
        {}
      containers:
        - name: rancher-blue
          securityContext:
            {}
          image: "bgulla/rancher-demo:latest"
          imagePullPolicy: IfNotPresent
          env:          
          - name: COW_COLOR
            value: "blue"
          - name: METADATA
            value: "Deployed via Fleet"
          - name: SHOW_VERSION
            value: "true"
          - name: VERSION
            value: "0.1"
          - name: TITLE
            value: "Rancher demo"  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 4m
              memory: 445Mi
            limits:    
              memory: 445Mi
      priorityClassName: high-priority
      nodeSelector:
        fav_color: blue
      tolerations:
      - key: "lights"
        operator: "Exists"
        effect: "NoSchedule"
