apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-white
  labels:
    app.kubernetes.io/name: rancher-demo
    app.kubernetes.io/instance: white
spec:
  replicas: 12
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demo
      app.kubernetes.io/instance: white
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-demo
        app.kubernetes.io/instance: white
        blinkt: show
        blinktColor: FFFFFF
    spec:
      securityContext:
        {}
      containers:
        - name: rancher-white
          securityContext:
            {}
          image: "bgulla/rancher-demo:latest"
          imagePullPolicy: IfNotPresent
          env:          
          - name: COW_COLOR
            value: "white"
          - name: METADATA
            value: "Deployed via Fleet"
          - name: SHOW_VERSION
            value: "true"
          - name: VERSION
            value: "0.1"
          - name: TITLE
            value: "Rancher demo"  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 4m
              memory: 445Mi
            limits:    
              memory: 445Mi
      priorityClassName: med-priority
